### PR TITLE
Invalid file type is shown in XML as type="Assembly" - Issue18

### LINKED ISSUE #18: Invalid file type is shown in XML as type="Assembly"
@CharliePoole commented on [Mon Dec 28 2015](https://github.com/nunit/nunit/issues/1163)

This doesn't get noticed in the console runner, but the gui uses the type to display information about the node. When I try to open package.config, it lists Type: Assembly for it.

When the engine creates a test-suite node for a non-runnable file, it should only use type="Assembly" if the extension is .dll or .exe. For anything else, it should use some other value, possibly "Unknown".

### PR DESCRIPTION
**Pull request by constructor-igor**
Implemented type "Unknown" for a non-runnable files with no extension .dll or .exe.
Warning:  WarningsAsErrors - off, because compilation problems.

Fixes #18

### CODE REVIEW

**Comment by CharliePoole** [comment]
Please add a description that says what you are fixing.

**Comment by rprouse** [comment]
@constructor-igor, when entering your pull requests, 

- please make the title a short description of the issue you are fixing
- the description should explain your evaluation of what was wrong and how you fixed it
- the description should include Fixes #18 so that the issue and the pull request are cross referenced and the issue is closed when the PR is merged

We have a lot of pull requests to review, so giving us as much information as possible helps us get it done more quickly.

Thanks

**Comment by CharliePoole** [comment]
@constructor-igor Is the warning as errors problem local to you or does it come up in CI?

**Comment by rprouse** [comment]
I have reverted the treat warnings as errors changes. This can be reviewed and merged once CI passed.

**Comment by rprouse** [comment]
Looks good to me. Just waiting for the Linux CI builds on Travis to pass before merging.

**Pull request merged**
