### PR TITLE
Add a few tests for an issue under open investigation

### PR DESCRIPTION
**Pull request by stevenaw**
Relates to #1510

### CODE REVIEW

**Comment by CharliePoole** [comment]
@stevenaw I'm back from my class and looking this PR over. Do I understand correctly that the first commit is what _should_ work, while the second simply changes the tests to reflect current behavior?

**Comment by stevenaw** [comment]
Welcome back @CharliePoole 

Admittedly, my investigation here was partly self-exploration. The first commit was to try what had been attempted in the original reporter's repro, and then how the tokenizer interpreted it. The second commit updates it to be enclosed in commas after I noticed other places where you had recommended the same. This, of course, changed the tokenizer output and so I updated the test accordingly.

My own lack of knowledge about this part of the codebase prevents me from saying which of these two is correct, though the fact that the engine could parse the comma-enclosed value but the framework couldn't resolve it to a test had me was beginning to wonder if it were a framework issue.

I'd welcome your investigation here if you are able. If you did, please do feel free to close this PR or to build upon it depending on the direction it may go.

**Comment by CharliePoole** [comment]
Thanks, that gives me the context I wanted. I'll adopt this branch and see what I can figure out. It really seems that we need tests to verify the XML content of each example as well as tests that exercise the framework using the same filters.

**Comment by CharliePoole** [comment]
Replaced by PR #1519

**Pull request closed without merging**
