### PR TITLE
Integrate TestAssemblyLoadContext changes to version315

### PR DESCRIPTION
**Pull request by veleek**
As per discussion in #1370, this change integrates all of the updates to TestAssembyLoadContext (nee CustomAssemblyLoadContext) from the `main` to the `version315` branch.  Unfortunately, there have been some changes to some of the packaging bits and pieces in order to add in the extra library used by TestAssemblyResolver, so I had to get those changes all merged as well.

Here is the set of commits that touched `TestAssemblyLoadContext.cs` and `TestAssemblyResolver.cs` (from oldest to newest) and what I did to resolve them:

3f854b20e4ea7e42ba7ae0d7bf81af902a6bc8fd - Manual resolution needed to deal with packaging changes due to new dependency.
f11499a418d5b5bb7ecdd5c91b2686fff4e32f74 - Do we need this change?  I merged the modifications to TestAssemblyLoadContext but just ignored everything else related to project changes for extra tests.
485153dd0b414f71e2432aadc1028afce114e7cf - Clean
b01ad3e6b61ad48640a90d8dbabbcc1dbb14b578 - Clean
38d141eaa8cf71c1095aeb5050b9a5641c71452d - Clean
462d9d25da21d4fa9558f5ab9db8f2c3d1dbd4b8 - Clean

> Note: Merge commits c7566820da5a444659e61469fe21afd262ba445d, b92df46ec6a8ca62963c9d5057c3dbe1746820a7, b92df46ec6a8ca62963c9d5057c3dbe1746820a7, 8f472b0ad29404593f3084622dac88ba6e5c5191, and 887516ae976a4b1b2dcc7704fe110080f9ec1a4b were just ignored.

### CODE REVIEW

**Comment by veleek** [comment]
@OsirisTerje - This is probably more complicated than I'm assuming you were expecting when you suggested raising this PR for `version315`.  Before I spend any time testing this and verifying it works, can you confirm that you think this is a reasonable change to make?  I have not even bothered building this yet.

If you _do_ still want to go ahead with this, is there anything that I need to know around building/testing the changes that were done to the different packages files (cake/choco/msi)?

**Comment by OsirisTerje** [comment]
I think we should try to move on with this.  There are a comprehensive suite of tests in the console.  Do all of them run?  

````
build --target test
```

PS:  I am on travel now, and my laptop doesnt have all the frameworks installed, and slow internet lines, so I can't check it.  I also got some vulnerability warnings.

**Comment by veleek** [comment]
Okay, finally found a few minutes to troubleshoot this.  Had to add some extra dependencies for .NET 5 and .NET 6.  Verified tests all pass on Windows, I don't have any way to easily test on other platforms.   

Attached build/test log given the above command.
[nunit_build.log](https://github.com/nunit/nunit-console/files/14361365/nunit_build.log)

**Comment by veleek** [comment]
@OsirisTerje - Quick bump in case this you missed this one.

**Comment by OsirisTerje** [comment]
Not missed, but lack of time.  I need to work through the different changes you have done, to ensure the bugs in 3.16.X is not coming over.  Even if you're pretty sure it is, a second look here should be done.

**Comment by veleek** [comment]
Sounds good!  Absolutely no pressure intended from my end.   I'm not blocked in any way, just wanted to make sure it wasn't lost in the cracks (because I took so long for the original follow up).

**Comment by OsirisTerje** [comment]
@veleek 
1. Can you redirect this PR to branch  "version3X" ?
2. Any possibility you could test that the engine created from this PR will work with the NUnit3TestAdapter?

**Comment by veleek** [comment]
> 1. Can you redirect this PR to branch  "version3X" ?

Okay, I just rebased this onto version3X and retargeted the PR.  I had to make some extra changes because .NET 7 and 8 support were added, but everything seems to build and test fine now.

> 2. Any possibility you could test that the engine created from this PR will work with the NUnit3TestAdapter?

Is there some semi-automated way to do this?  I got as far as figuring out how the nunit3-vs-adapter repo builds, and I feel like I would need to publish a NuGet package with my updated binaries, then rebuild the adapter and then pull it into a test project.

I did the bare minimum testing and it seemed to work:
1. Grab NUnit3.TestAdapter.dll from the published NuGet package
2. Grab nunit.framework/engine.dll et. al. from my local build.
3. Create a project and manually add references to those DLLs.
4. Create a test and run it from Visual Studio and verify it works.

**Comment by OsirisTerje** [comment]
@veleek I merged this now, but noticed that the `build --target package` now fails with not being able to build the netcore package, due to a missing Microsoft.Extensions.DependencyModel.dll.
Can you please have a look?

**Comment by veleek** [comment]
I just opened #1406 to deal with this.

**Pull request merged**
