### PR TITLE
Preparing for 3.6.1 Hotfix Release

### PR DESCRIPTION
**Pull request by rprouse**
**Do not merge** I will create a merge branch to bring the changes back into master without the version changes.

I am preparing the 3.6.1 release based on this code. Review now or forever hold your peace 😄

### CODE REVIEW

**Comment by rprouse** [comment]
The erroneous comments are on one of the commits that got pulled in from the previous pull request. They can be ignored.

**Comment by rprouse** [comment]
I have reviewed the code and see the following changes which are what I expect,

- Increment version to 3.6.1
- Add to Changes.txt
- Changes from PR #183

The one AppVeyor build is failing because this is non-mergable because of the version change conflicts.

**Comment by CharliePoole** [comment]
This looks right to me.

**Comment by rprouse** [comment]
Initial release built and released. Still need to do the MSI release, but that is in the dist repo and I need to wait for the NuGet packages to go live first, so I am closing this PR. I will prepare the merge to master now.

**Comment by Trass3r** [comment]
Is it normal that https://www.nuget.org/packages/NUnit/ shows NUnit 3.6.1 as released on Sunday, February 26, 2017?
https://www.nuget.org/packages/NUnit.ConsoleRunner/ has the correct date.

**Comment by rprouse** [comment]
@Trass3r it is normal. The framework and console are separate releases and may diverge in version.

**Pull request closed without merging**
