### PR TITLE
Remove the -err command line option that was never completed

### LINKED ISSUE #360: CommandLineOption --err does not write error input to ErrorFile
Hi guys,

I am trying this:
"nunit3-console.exe MyTestAssembly_uTest.dll --err=ErrorOutput.txt --out=StandardOutputfile.txt"

The assembly to test has only one test:
```C#
public void SampleTest()
       {
            Console.Error.WriteLine("I am a standard error output.");
            TestContext.Error.WriteLine("I am a standard error output.");
        }
```
After execution of the test case above, the file which should contain the error output is always empty. 
I realized that the strings are written to the StandardOutputfile.txt.

Can you help me guys?

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #360 

Abandoning the other PR and just removing the command line option that does nothing.

### CODE REVIEW

**Comment by rprouse** [comment]
Looks like I missed removing one class field. Build failures are from the warning, just not sure why some passed...

```
The private field `NUnit.ConsoleRunner.ConsoleRunner._errorWriter' is assigned but its value is never used
```

**Comment by CharliePoole** [comment]
Travis always fails on unused fields.

**Comment by rprouse** [comment]
> Travis always fails on unused fields.

The Mono:Latest builds passed though. I wonder what changed in Mono? 😕

**Comment by jnm2** [comment]
> ConsoleRunner.cs(64,28): error CS0414: Warning as Error: The private field `NUnit.ConsoleRunner.ConsoleRunner._errorWriter' is assigned but its value is never used

Would have been caused by these two lines:

https://github.com/nunit/nunit-console/blob/91986e7529723fd8ea9bee787ee8104f89bf63e6/src/NUnitConsole/nunit3-console/nunit3-console.csproj#L28

https://github.com/nunit/nunit-console/blob/91986e7529723fd8ea9bee787ee8104f89bf63e6/src/NUnitConsole/nunit3-console/nunit3-console.csproj#L39

What made AppVeyor and Mono Latest ignore that though? That's weird.

**Comment by jnm2** [comment]
Maybe Platform did not evaluate to `AnyCPU`? Either way, we should probably move that property to an unconditional property group. I'm not a fan of the VS project properties UI.

**Pull request merged**
