### PR TITLE
Removed ClrVersion from RuntimeFramework

### LINKED ISSUE #1176: Exception when targeting .NET Framework with .NET 7 installed
```
Exception System.TypeInitializationException,    Exception thrown executing tests in B:\repos\Libraries\New folder\bin\Debug\net48\New folder.dll
The type initializer for 'NUnit.Engine.Services.RuntimeFrameworkService' threw an exception.
   at NUnit.Engine.Services.RuntimeFrameworkService.ApplyImageData(TestPackage package)
   at NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(TestPackage package)
   at NUnit.Engine.Runners.MasterTestRunner.GetEngineRunner()
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 88
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 275
InnerException: System.ArgumentException: Unknown framework version 7.0
Parameter name: version
   at NUnit.Engine.RuntimeFramework.GetClrVersionForFramework(Version frameworkVersion)
   at NUnit.Engine.RuntimeFramework..ctor(RuntimeType runtime, Version version, String profile)
   at NUnit.Engine.RuntimeFramework.GetNetCoreRuntimesFromDirectoryNames(IEnumerable`1 dirNames)
   at NUnit.Engine.RuntimeFramework.FindDotNetCoreFrameworks()
   at NUnit.Engine.RuntimeFramework.FindAvailableFrameworks()
   at NUnit.Engine.RuntimeFramework.get_AvailableFrameworks()
   at NUnit.Engine.Services.RuntimeFrameworkService..cctor()
No test is available in B:\repos\Libraries\New folder\bin\Debug\net48\New folder.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

## Reproduce
1. Install .NET 7 SDK
2. Create an unit test project by using `dotnet new nunit`
3. Update all dependencies to latest version
4. Target `net48`

## Full csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <RootNamespace>New_folder</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NUnit.Analyzers" Version="3.3.0" />
    <PackageReference Include="coverlet.collector" Version="3.1.2" />
  </ItemGroup>

</Project>
```

### PR DESCRIPTION
**Pull request by manfred-brands**
Decision logic moved to Runtime class.

Fixes #1176

### CODE REVIEW

**Comment by CharliePoole** [comment]
Thanks for doing this. It's a nice simplification of the code.

Some of the methods in the RuntimeFramework and Runtime classes are oddly named, but they have been that way for a while. We should pay attention to naming when we replace the class. Especially: Matches vs Supports vs CanLoad!

FYI, The Azure build isn't intended to be running except for specially named branches right now, but it's not set up right so I'm just ignoring the failures till it's fixed.

**Comment by CharliePoole** [comment]
Whoops... changed the issue fixed from #1176 to #1177

**Comment by tsmoreland** [comment]
any ETA on this being released?  Or should we just be building a local version instead for a while?

**Comment by tsmoreland** [comment]
-dev is fine, I've been using nunit3-console command line to run a test which has references to a wxiproj so can't use ```dotnet test``` directly, (maybe it's possible but use of nunit3-console was the faster solution), it's run as part of a CI pipeline which pulls down the command line tool to a fresh container, if I can get an update version from myget that'll work (I'll check that now)

**Pull request merged**
