### PR TITLE
Fixing directory separators for mono

### LINKED ISSUE #68: Incorrect path of dlls extracted from sln file
I love the feature of getting all assemblies extracted from the **solution file**, because it eases the CI scripts for us. However when testing on Linux, the following statement:

`mono ./src/T_GitLabCi/packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./src/T_GitLabCi/T_GitLabCi.sln /noresult`

results in

`Could not find file "/builds/kataik/gitlab_test/src/T_GitLabCi/T_GitLabCi\T_GitLabCi.csproj"`

Please notice the backslash between the file name and the directory path.

### PR DESCRIPTION
**Pull request by kataik**
fixes #68

### CODE REVIEW

**Comment by CharliePoole** [comment]
Did you investigate why the tests were passing? I'm curious.

This looks like a good change but because I've already moved the extension to its own repo, I'll have to merge it there rather than to nunit-console.

**Comment by kataik** [comment]
Sure, it was bad luck. If the test resource was specified like this: `@"myfolder\myfile.ext"` and the home folder on a Linux looks like this: `/usr/kataik/home` then on Mono, it is going to look like this: `/usr/kataik/home/myfolder\myfile.ext`, where **myfolder\myfile.ext** is the name of the file. The tests were wrong in the same way the code was.

New repo? Will the console be placed somewhere else?

**Comment by rprouse** [comment]
The console will continue to be hosted here, we are just moving the extensions out to their own repository.

**Comment by rprouse** [comment]
@CharliePoole if this looks good, could we merge here, then push to the new repo? Or have you already cleaned up to a point where that would be difficult?

**Comment by CharliePoole** [comment]
We could merge it but the two changed files are to be deleted, so it didn't make sense to me.

**Comment by rprouse** [comment]
If you are good with the changes, let's figure out how to get it across and get this closed. Shall I push it across and open a new PR?

**Comment by CharliePoole** [comment]
@rprouse As I commented above, I was planning to merge it manually. But if you would rather do a PR that's fine with me.

**Comment by rprouse** [comment]
@CharliePoole I was just offering. I know you are busy with the renos right now :smile:

**Comment by CharliePoole** [comment]
I am indeed and anything you can do to help is appreciated. However, this merely involves completely replacing two files I haven't changed, but which are in the new repo. It's easy enough to do either way.

I'm actually a bit more concerned about how the changes to nunit-console will get merged in now that the release PR has already been created. My strategy has been to not make any changes to the nunit-console project until after the separate extensions are ready for use.

**Comment by rprouse** [comment]
>I'm actually a bit more concerned about how the changes to nunit-console will get merged in now that the release PR has already been created. My strategy has been to not make any changes to the nunit-console project until after the separate extensions are ready for use.

I had planned on merging latest from master into the release PR or rebasing on master before we start the release. Worst case, I abandon that PR and redo the CHANGES.txt. The only intention of the PR was to have a safe place to keep the changes I've started compiling. I started cleaning up some no longer needed files, maybe that was premature, so I am happy to drop the PR.

**Comment by CharliePoole** [comment]
No need to drop it if you're going to do the additional merge. I was thinking it would require me to do my changes differently, but if all I have to do is get them to master, I'm happy. :smile:

**Comment by rprouse** [comment]
@kataik I have copied your changes from this PR over to a new PR at nunit/vs-project-loader#2. Sorry, I had to do it manually, so the commit will not be credited to you. If you would like the commit, let us know and you can do a new PR. Otherwise, I would appreciate it if you gave it a quick look and make sure that I haven't included anything unintentionally.

Thanks for your help and the contribution. I am closing this PR as the code is now in the new repo.

**Pull request closed without merging**
