### PR TITLE
Pass whitespace in work directory path to agents correctly (Based on #572)

### LINKED ISSUE #571: Space characters in the work directory path are not properly handled
When nunit3-console constructs the command line to run an agent, it does not properly double-quote the work directory path, that causes the runner to fail.

Here is a sample internal trace log:

```
14:40:58.747 Debug [ 1] TestAgency: Command line: "C:\Contoso\bin\Release With Spaces\TestPackage\nunit-agent.exe" f3ab647d-8aa4-4cb9-8032-a55f48aae46e tcp://127.0.0.1:60774/TestAgency --pid=16708 --trace:Debug --work=C:\Contoso\bin\Release With Spaces\TestPackage
14:40:58.748 Debug [ 1] TestAgency: Waiting for agent {f3ab647d-8aa4-4cb9-8032-a55f48aae46e} to register
14:40:59.350 Error [ 1] ProcessRunner: Failed to run remote tests Unable to acquire remote process agent
```

As you may see, the last part:
```
--work=C:\Contoso\bin\Release With Spaces\TestPackage
```

contains the path without quotes.

The problem is in the "nunit-console-3.9\src\NUnitEngine\nunit.engine\Services\TestAgency.cs" source file inside LaunchAgentProcess method. 

Current code looks like this:

```
agentArgs += " --work=" + workDirectory;
```

The fixed version:

```
agentArgs += " --work \"" + workDirectory + "\"";
```

For now, we'll be using our custom fixed nunit-console build, but it would be great if the issue is fixed in the next official release. Thank you!

### PR DESCRIPTION
**Pull request by ChrisMaddock**
This is @Funbit's contribution from #572, with @mikkelbu's fix applied. Moving both of these into this new PR, so I can merge into master in time for the 3.10 release.

Based on the multiple reviews in #572, I'll merge this as soon as CI has run.

Fixes #571

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
^ FYI @rprouse - I had the same issue of @dnfclas thinking I hadn't signed the CLA before, when I definitely have. I just signed it again.

**Comment by ChrisMaddock** [comment]
Oops, can't approve my own PR's! @nunit/engine-team - would appreciate some eyes on this please. 😄

**Comment by ChrisMaddock** [comment]
Thanks Mikkel!

**Comment by mikkelbu** [comment]
You are most welcome :).

**Comment by rprouse** [comment]
I had to sign the contribution agreement again too. Maybe it is an updated version? We'll have to see if it happens again.

**Pull request merged**
