### PR TITLE
System.Configuration.ConfigurationErrorsException thrown in multiple domain mode. #58

### PR DESCRIPTION
**Pull request by mrsneeze**
Fix for issue #58

### CODE REVIEW

**Comment by rprouse** [comment]
In what case was the package.Name null?

**Comment by mrsneeze** [comment]
It happens if you run nunit on itself with no other parameters, or run a single assembly.

**Comment by rprouse** [comment]
What do you mean by "It happens if you run nunit on itself with no other parameters?"

**Comment by mrsneeze** [comment]
as in: nunit3-console nunit3-console.exe

It was the first assembly I could think of to test that it starts :)

**Comment by rprouse** [comment]
@CharliePoole I think this is good to merge once we update from master. We should look at the package being null, but I think that is separate from this PR. Can you give it a quick second review?

@mrsneeze, can you merge latest from master or rebase? If not, we can do it for you.

**Comment by rprouse** [comment]
@mrsneeze skip the update from master. I turned off the requirement to be up to date with master as I already did on the main framework repository. It sounds like a good idea, but every contributor usually has to update before their PR goes in and it ends up being a race condition with multiple PRs 👊 😦

**Comment by rprouse** [comment]
@nunit/core-team this PR needs a second review.

**Comment by rprouse** [comment]
Once again, @nunit/core-team this needs a second review. This PR has been outstanding for a long time, so I would like to get it merged. I will merge soon if no reviewer is available.

**Comment by CharliePoole** [comment]
Looks OK to me

**Comment by rprouse** [comment]
Thanks for the contribution @mrsneeze. Sorry it took so long to get merged.

**Pull request merged**
