### PR TITLE
Ensure that assembly-level errors are actually displayed by console runner

### LINKED ISSUE #350: Invalid assemblies no longer give an error message
In the NUnit3 console runner 3.7, the argument `x.dll` gives an error message indicating the file was not found. Typing `x.junk` gives a message saying that the file type is not known.

In the current master build, the run fails without specifying a message in both cases.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #350 

This is the console part of the fix. I'll do the framework fix next.

As I envision this, the console should not need any changes once the framework fix is in. However, the console still has to deal with older framework versions and it is for those versions that this PR is targeted.

The problem is with failures, errors or warnings that come from child tests of a suite, but which do not have the `site` attribute set to `Child`. That means the runner assumes the suite itself is the cause of the error. A previous fix solved the problem by ignoring any suites without a `site` attribute but that causes the problem described in the issue. Assembly not found and similar errors don't use the site at all.

After experimenting with various approaches, including looking at the `type` attribute, I decided that the best way, although ugly, was to examine the message used. For all our releases, we have used constant messages for suites with a failed or warning status due to problems with the child tests. I'm using those messages to decide whether a suite with no site specified should actually have the `Child` value instead of the default `Test` value.

This is pretty adhoc, but fixes on top of existing framework releases often are. Please review with that in mind and try to see if you can think of any situations where this will not work.

### CODE REVIEW

**Comment by CharliePoole** [comment]
@rprouse If this looks good to you, let's merge without waiting for an IOS build, which may never come.

**Comment by jnm2** [comment]
We need to do something about Travis. Maybe the .NET Foundation can get us a different service that does OSX.

**Comment by CharliePoole** [comment]
I can force the merge at any time, of course.

This problem has been going on for a while. Should we make the iOS build optional? Disable entirely?

**Comment by CharliePoole** [comment]
Yes, we previously had these builds set up to allow failure. If you set it up right, the build is flagged as complete even if the jobs that allow failure have not started. We changed to requiring it because we wanted to be sure that it worked on iOS.

**Pull request merged**
