### PR TITLE
Issue104

### PR DESCRIPTION
**Pull request by constructor-igor**

### CODE REVIEW

**Comment by CharliePoole** [comment]
This is so small, I'll just go ahead and merge.

**Comment by ChrisMaddock** [comment]
This seems to also turn off WarningsAsErrors for various projects - was that intentional?

**Comment by rprouse** [comment]
I am fine with the change itself, but I am also concerned that this is turning off warnings as errors in several projects as mentioned in the other pull request. I would prefer to see warnings as errors left on. @constructor-igor can you comment? I am thinking of reverting this merge and requesting changes.

**Comment by constructor-igor** [comment]
@rprouse I had a compilation problem with WarningsAsErrors.
I don't know how to fix. Could you help me?

**Comment by rprouse** [comment]
@constructor-igor can you post the warnings in one of the other pull requests you have open? I will help you with them there.

**Pull request merged**
