### PR TITLE
Fix exception when targeting .NET Framework with .NET 7 installed

### PR DESCRIPTION
**Pull request by YuhanKun**
Related to: 
nunit/nunit-console#1176
https://github.com/nunit/nunit-console/issues/1014

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nunit/nunit-console?pullRequest=1175) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nunit/nunit-console?pullRequest=1175) before we can accept your contribution.<br/><br/>:x: YuhanKun [sign now](https://cla.dotnetfoundation.org/nunit/nunit-console?pullRequest=1175)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nunit/nunit-console?pullRequest=1175) it.</sub>

**Review by manfred-brands — APPROVED** [review]
LGTM, Only 6 months after I added the line for 6.

**Comment by CharliePoole** [comment]
I see no problem with this so I'm merging. The Linux and MacOS failures in azure are a separate problem. 

Note that this change does _not_ enable you to run tests targeting .NET 7.0. As with net 6.0, that requires more work.

@YuhanKun Thanks for your contribution.

@manfred-brands Welcome! I see you accepted my invitation. It's a bit annoying that GitHub doesn't notify me when someone accepts. Please contact me by email so we can talk about your participation (charliepoole AT gmail DOT com)

**Comment by CharliePoole** [comment]
Sorry... I indicated I was merging this four days ago but I appear not to have done so. Merging now!

**Comment by ankushjain358** [comment]
.Net 7 is released today and nunit is working fine. It's tested using **NUnit3TestAdapter** [v4.3.0](https://www.nuget.org/packages/NUnit3TestAdapter/4.3.0)

**Comment by CharliePoole** [comment]
@ankushjain358 True but not relevant here. This is about testing with the console runner, not the test adapter. :-)

However, console runner version 3.16.0-dev00073 does support testing under today's release of .NET 7.0. The full release of 3.16 will be out next week.

**Pull request merged**
