### PR TITLE
Increment nunit.engine.api assembly version inline with other engine dlls

### LINKED ISSUE #801: Begin incrementing EngineApiVersion with every release, as per Engine version
To prevent issues like #800 and #424.

Historically, the engine api assembly version has remained static at 3.0, whilst the engine version increments with each release. The intention of this was to support a [centrally installed engine](https://github.com/nunit/nunit-console/issues/800#issuecomment-664633972), which is an concept that didn't end up gaining much traction, as the engine developed over the years.

I suggest from 3.12, we start incrementing the API assemblies version in line with the main engine version.

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Fixes #801. See discussion on #800 for reasonings behind this change.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
Hmm, Travis failed again. This hasn't happened in months, but has now happened 2/3 runs since merging #799. I wonder if we should back it out...

**Comment by ChrisMaddock** [comment]
Thanks Joseph!

**Comment by ulrichb** [comment]
When will this be released? Is there a workaround in the meantime? 

I tried different combination of NUnit and NUnit3TestAdapter package dependencies and all of them fail with R# :(

**Comment by ChrisMaddock** [comment]
Hi @ulrichb,

The latest NUnit3TestAdapter and latest R# should work together. If you're finding that not to be the case, please open a new issue - I suspect you might be encountering a different problem.

On this change, not totally sure if it will be released yet, as it's caused another issue - see #807. Not totally sure what the solution is to all this yet...

**Comment by ChrisMaddock** [comment]
Hi @ulrichb,

The latest NUnit3TestAdapter and latest R# should work together. If you're finding that not to be the case, please open a new issue - I suspect you might be encountering a different problem.

On this change, not totally sure if it will be released yet, as it's caused another issue - see #807. Not totally sure what the solution is to all this yet...

**Pull request merged**
