### PR TITLE
Single YAML-based Azure DevOps build

### PR DESCRIPTION
**Pull request by jnm2**
Pretty much a copy of https://github.com/nunit/nunit/pull/3096. Closes https://github.com/nunit/nunit-console/issues/508.

**When this PR is merged**, whoever gets there first should set https://nunit.visualstudio.com/NUnit/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=13&view=Tab_Triggers to stop overriding the YAML triggers and allow pushes and PRs to trigger the build for validation:

image

### Test results

image

### Artifacts

The Windows build runs the Package target and creates an artifact named Package (maybe later we should split into multiple artifacts):

image

### CODE REVIEW

**Comment by jnm2** [comment]
Looks like AppVeyor's unhappy with my enjoyment of underscores in branch names. We never did https://github.com/nunit/nunit/pull/2187 to this repo. I'll fix.

**Comment by ChrisMaddock** [comment]
Yay - awesome! 

Hoping to get 3.10 out soon - given this is non-funcationlity based, do you mind if I come back and look through this after that? Although it's cool that we have a clean macOS CI run available before the release! 😄

**Comment by jnm2** [comment]
@ChrisMaddock Absolutely fine with me. =)

**Comment by jnm2** [comment]
Moved a commit to its own PR: https://github.com/nunit/nunit-console/pull/579

**Comment by rprouse** [comment]
@ChrisMaddock is travelling right now, so I am going to go ahead and merge. Thanks for getting this done.

**Comment by rprouse** [comment]
I've stopped overriding the YAML triggers on both triggers.

**Comment by ChrisMaddock** [comment]
Fine by me - thanks Rob/Joseph!

**Pull request merged**
