### PR TITLE
Remove CF, Silverlight and PORTABLE functionality

### LINKED ISSUE #103: The switch statement does not cover all values of the 'RuntimeType' enum: NetCF.
I test PVS_Studio and find several minor issues.
Probably, the issues should be checked and fixed,

V3002 The switch statement does not cover all values of the 'RuntimeType' enum: NetCF. RuntimeFramework.cs 98

``` c#
        private void InitFromFrameworkVersion(Version version)
        {
            this.FrameworkVersion = this.ClrVersion = version;

            if (version.Major > 0) // 0 means any version
                switch (Runtime)
                {
                    case RuntimeType.Net:
                    case RuntimeType.Mono:
                    case RuntimeType.Any:
                        switch (version.Major)
                        {
                            case 1:
                                switch (version.Minor)
                                {
                                    case 0:
                                        this.ClrVersion = Runtime == RuntimeType.Mono
                                            ? new Version(1, 1, 4322)
                                            : new Version(1, 0, 3705);
                                        break;
                                    case 1:
                                        if (Runtime == RuntimeType.Mono)
                                            this.FrameworkVersion = new Version(1, 0);
                                        this.ClrVersion = new Version(1, 1, 4322);
                                        break;
                                    default:
                                        ThrowInvalidFrameworkVersion(version);
                                        break;
                                }
                                break;
                            case 2:
                            case 3:
                                this.ClrVersion = new Version(2, 0, 50727);
                                break;
                            case 4:
                                this.ClrVersion = new Version(4, 0, 30319);
                                break;
                            default:
                                ThrowInvalidFrameworkVersion(version);
                                break;
                        }
                        break;

                    case RuntimeType.Silverlight:
                        this.ClrVersion = version.Major >= 4
                            ? new Version(4, 0, 60310)
                            : new Version(2, 0, 50727);
                        break;
                }
        }
```

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Relates to #406, fixes #103. 

Runtime Framework code still blows my mind a little...this is a baby step towards simplifying things. I believe these items are remnants of when this code was shared with the framework.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
> Some of the references to unsupported frameworks are intended to allow identifying test assemblies that target a framework we don't support. 

I left those checks in place. 🙂

**Comment by CharliePoole** [comment]
@mikkelbu We treat PORTABLE as if it were a platform, just like NETCF and SILVERLIGHT. Of course, it's actually a set of platforms. We don't build any of them any longer.

Your comments make sense to me too.

**Comment by ChrisMaddock** [comment]
Thanks Mikkel! I hadn't particularly been planning to remove portable with this...but I had removed a few that had caught my eye as I'd gone through - so makes sense to get rid of the final few! Changes made. 🙂

**Comment by ChrisMaddock** [comment]
Done and merged - thanks!

**Pull request merged**
