### PR TITLE
3.5 release

### PR DESCRIPTION
**Pull request by rprouse**
**Do Not Merge**

This is the branch for the 3.5 release. I have updated the CHANGES.txt with fixes from the main NUnit repository prior to the repository split. I have also deleted unused files.

We can continue from this point after the framework release.

### CODE REVIEW

**Comment by CharliePoole** [comment]
I thought we were going to hold this till after the separate extensions were released.

**Comment by ChrisMaddock** [comment]
Just a note: https://github.com/nunit/nunit-distribution/issues/2 needs doing before this release - I can hopfully get it done tomorrow. Just need to figure out if there's a better way to handle it, as the TC extension was previously installed without a wix GUID.

**Comment by ChrisMaddock** [comment]
Or anyone else can feel free to do it, if you want to move quicker! :smile:

**Comment by rprouse** [comment]
I am going to hold this until the extensions are done. Working on the framework release, when I generated the list of changes, there were many console / engine issues from the split, so I decided to start building the change list here. 

We can merge in any new changes as we go.

**Comment by rprouse** [comment]
I have merged latest from master into this branch. For release I think the following is outstanding,

- [ ] Update nunit-distribution to create a ZIP file containing the extensions
- [ ] Complete remaining [issues in the 3.5 Milestone](https://github.com/nunit/nunit-console/milestone/1)
- [ ] Merge latest from master to include the issues in this release
- [ ] Update CHANGES.txt to include issues resolved in this repository
- [ ] Build and release the console/engine
- [ ] Build and release the MSI and ZIP from distribution. Should those be a attached to the GitHub release in this repo?

**Comment by CharliePoole** [comment]
I agree with the list of tasks. Regarding the msi and zip, I'm a bit uncertain as to how to do it. In principle, I would expect it to be a release of the nunit-distribution project, but users are accustomed to getting them here. Maybe we can put a notice with the release notes that tells them where to look. Part of what I was assuming for the separate  distrib project is that we would not update it for hot fixes, so it makes some sense for it to be separate.

**Comment by rprouse** [comment]
3.2.8 is still failing despite merging in master. Didn't we disable it or was that the other repos?

**Comment by CharliePoole** [comment]
Other repos. I just pushed a change to master dropping mono 3.2.8 entirely. We're still building 4.2.4 and latest, with latest allowed to fail. All are passing right now, but of course, latest can always break. I think we should review the hard-coded 4.2.4 periodically and update it as needed.

**Comment by CharliePoole** [comment]
I'll add further changes to the CHANGES file tomorrow and release.

**Comment by ChrisMaddock** [comment]
> Other repos. I just pushed a change to master dropping mono 3.2.8 entirely. We're still building 4.2.4 and latest, with latest allowed to fail. All are passing right now, but of course, latest can always break. I think we should review the hard-coded 4.2.4 periodically and update it as needed.

I'll add this to the framework repo with my current work on nunit/nunit#1609

**Comment by CharliePoole** [comment]
@nunit/core-team @nunit/contributors 
Once the CI passes, I believe this is ready to use for the 3.5 release. Please review.

**Comment by rprouse** [comment]
I reviewed about an hour ago and it looks good. I checked the branches and PRs and the only thing missing are the changes from #92, but that is just a change to the README, so doesn't need to be merged into this branch.

I say ship it :shipit: 👍

**Comment by rprouse** [comment]
Closing this PR now that the release is done. Working on the PR to merge the changes back into master.

**Pull request closed without merging**
