### PR TITLE
Update --labels switch (continued)

### LINKED ISSUE #24: Update --labels switch with option to show real-time pass/fail results in console runner
@dybs commented on [Fri Aug 12 2016](https://github.com/nunit/nunit/issues/1738)

When running a large number of test cases, it would be nice to see the pass/fail status of each case in the console as it completes.  Using --labels=All, I can see which tests have run, but the results are not available until all cases have completed.  Seeing which cases fail during a long scenario would allow me to investigate the failures while the remaining tests continue to run.  It also has the advantage of knowing which cases passed/failed if the test scenario happens to crash and doesn't get to write the result file.

Per the discussion in #1735 some ideas are to modify --labels with the following options:
- Results -> same behavior as =All, but includes a Pass/Fail/Error status
- Before -> shows the test case before it executes, and appends the status after the test completes.  Similar to On.
- After -> shows the test case and status together after the test case completes.

---

@CharliePoole commented on [Fri Aug 12 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239549055)

I like this idea, but I would modify/simplify it by preference:
- Off No change
- On No change
- Before / All shows test label when the test starts executing.
- After Shows all tests after they have completed, including status.

Note that All is described as it is supposed to work already. There's currently a bug in that it runs at the end of a test. We should fix that. We should keep All so as not to break existing usage.

The introduction of After means that we have to treat it as also meaning On. That is, if a test produces output, there should be a label before that output and another one after it, together with the test status..

The change should be made in both the console runner and nunitlite. Once we split the repos, this issue will need to be duplicated.

The fix is _relatively_ easy. Depending on who takes it, I can mentor them as needed.

---

@constructor-igor commented on [Sun Aug 14 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239676310)

Hi @CharliePoole,

Probably, I can start to work on the issue.
I checked all existing options of "--labels" parameter. Please, could you help me to understand suggested changes? I added sample with "--lablels=All". As I understand, the issue suggests to add "status" of each test?

image

thank you,
Igor.

---

@CharliePoole commented on [Sun Aug 14 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239684890)

Hi @constructor-igor - I've been meaning to poke you to see what you are up to. :-)

As you probably figured out, all the code is in Console's TestEventHandler and in NUnitLite's TestRunner. There are tests for TestEventHandler but not for TestRunner. :-(

I would first off fix the problem with All, which is supposed to be issued at the start of each test, not at the end. I think I broke this when I was fixing something else.

Once All is correct, you've got Before, since it's intended to work the same way.

After is the new thing, which is supposed to show status of the test. For that, I would use a combination of the `result` and `label` attributes to display a set of values like...
- Passed
- Failed
- Error
- Invalid
- Ignored
- Explicit
- Skipped
- Inconclusive
  In NUnitLite, you'll have the ResultState available to use for equivalent logic.

---

@constructor-igor commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239782084)

I am going to start from "All".
But, right now, I don't understand expected behavior of "All".
So, when I'll investigate code I'll contact with you.

---

@CharliePoole commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239783383)

You might try this sequence - a bit different order from my first suggestion:
- Change "All" in existing code everywhere to "After" because All is now incorrectly running after the test.
- Add status info to After
- Add "Before" to run before the test
- Add back "All" as a synyonym for Before

---

@constructor-igor commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239785294)

I try to build nunit by "build.cmd":
image

VS2013:
image

---

@CharliePoole commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239790081)

Are you using the latest master? Can you build in the IDE?

---

@constructor-igor commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239796767)

I cloned today and tried to build via build.cmd and IDE VS2013: same errors.

---

@CharliePoole commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239798656)

Using VS 2015?

---

@rprouse commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239803785)

I just got latest from master and ran `.\build.cmd` and it builds fine for me. Maybe do a full clean including deleting your packages folder and rebuild?

---

@constructor-igor commented on [Mon Aug 15 2016](https://github.com/nunit/nunit/issues/1738#issuecomment-239894381)

I could build nunit solution on other computer.
I tried to build on my computer again (downloaded master to new folder) and  see the error.

I investigate the issue and found, probably, same issues 
- https://github.com/nunit/nunit3-vs-adapter/issues/194
- https://github.com/nunit/docs/issues/44

I continue my investigation.

### PR DESCRIPTION
**Pull request by CharliePoole**
**Do not merge**
Fixes #24 

I created this new branch under the nunit organization, merging @constructor-igor 's PR #78. This will make it easier to collaborate, particularly by providing tests.

I added new tests to the code for multiple events. They are written so that the expected output is what the current code prodcues but there are comments regarding what the output should be.

In so doing, I uncovered a linux bug. The travis CI is failing because of unexpected `\r\n` strings in the output. IOW, we don't convert newline characters provided by the user. This may actually be a feature rather than a bug, in which case the test can simply be changed.

### CODE REVIEW

**Comment by CharliePoole** [comment]
Latest commits bring this up to date with master. In particular, it now builds as a 3.6 pre-release.

**Comment by rprouse** [comment]
>This may actually be a feature rather than a bug, in which case the test can simply be changed.

I think that we should respect the output that is provided, even if it is wrong. That said, will it end up creating mixed line endings in the test results? If so, then maybe we should convert. To be honest, I've never even looked at the line endings in our results files.

**Comment by CharliePoole** [comment]
@constructor-igor Any progress on this? Do you need any help?

**Comment by constructor-igor** [comment]
@CharliePoole I need a help:

> Make Use of BEFORE, ALL or AFTER supersets of On. By that I mean the labels will re-appear as needed each time tere is output from a different test. We will need tests of this, maybe based on the examples I gave in my earlier comment. One way to do it would be to replace the test for "On" with a boolean and set the boolean to true for all values of labels except OFF. I can write a test to show what I mean if it isn't clear.

**Igor**

> @CharliePoole, I want to continue, but I need help.
> Please, could you add test for the request?

**Comment by CharliePoole** [comment]
@constructor-igor I created the branch in order to give you the test. Look at the file changes.

**Comment by constructor-igor** [comment]
ok. I am going to continue this week.

**Comment by CharliePoole** [comment]
That's great. I'll watch for updates / questions.

**Comment by constructor-igor** [comment]
If I am not mistaken, method TestEventHandler.TestOutput used attribute "testname", instead of correct "fullname".
Probably, it's necessary to define "const" and use it everywhere?

image

**Comment by constructor-igor** [comment]
@CharliePoole, please, could you check my last changes? New added tests now work.

**Comment by CharliePoole** [comment]
I'm travelling so it may take a few days. @rprouse can you take a look?

**Comment by rprouse** [comment]
I will try to look today.

**Comment by rprouse** [comment]
@constructor-igor your tests need to take into account the newline character on non-windows systems. The tests are failing on Travis,

```
1) Failed : NUnit.ConsoleRunner.Tests.TestEventHandlerTests.MultipleEvents(System.String[],"Off","Immediate output from TEST1\r\nOutput\r\nfrom\r\nTEST1\r\n")
  Expected string length 46 but was 48. Strings differ at index 34.
  Expected: "Immediate output from TEST1\nOutput\nfrom\nTEST1\n"
  But was:  "Immediate output from TEST1\nOutput\r\nfrom\r\nTEST1\n"
  -----------------------------------------------^
at NUnit.ConsoleRunner.Tests.TestEventHandlerTests.MultipleEvents (System.String[] reports, System.String labels, System.String expected) <0x3548e80 + 0x000e7> in <filename unknown>:0
2) Failed : NUnit.ConsoleRunner.Tests.TestEventHandlerTests.MultipleEvents(System.String[],"On","=> TEST1\r\nImmediate output from TEST1\r\nOutput\r\nfrom\r\nTEST1\r\n")
  Expected string length 55 but was 57. Strings differ at index 43.
  Expected: "=> TEST1\nImmediate output from TEST1\nOutput\nfrom\nTEST1\n"
  But was:  "=> TEST1\nImmediate output from TEST1\nOutput\r\nfrom\r\nTEST1\n"
  ---------------------------------------------------------^
at NUnit.ConsoleRunner.Tests.TestEventHandlerTests.MultipleEvents (System.String[] reports, System.String labels, System.String expected) <0x3548e80 + 0x000e7> in <filename unknown>:0
3) Failed : NUnit.ConsoleRunner.Tests.TestEventHandlerTests.MultipleEvents(System.String[],"All","=> TEST1\r\nImmediate output from TEST1\r\nOutput\r\nfrom\r\nTEST1\r\n")
  Expected string length 55 but was 57. Strings differ at index 43.
  Expected: "=> TEST1\nImmediate output from TEST1\nOutput\nfrom\nTEST1\n"
  But was:  "=> TEST1\nImmediate output from TEST1\nOutput\r\nfrom\r\nTEST1\n"
  ---------------------------------------------------------^
at NUnit.ConsoleRunner.Tests.TestEventHandlerTests.MultipleEvents (System.String[] reports, System.String labels, System.String expected) <0x3548e80 + 0x000e7> in <filename unknown>:0
4) Failed : NUnit.ConsoleRunner.Tests.TestEventHandlerTests.MultipleEvents(System.String[],"Before","=> TEST1\r\nImmediate output from TEST1\r\nOutput\r\nfrom\r\nTEST1\r\n")
  Expected string length 55 but was 57. Strings differ at index 43.
  Expected: "=> TEST1\nImmediate output from TEST1\nOutput\nfrom\nTEST1\n"
  But was:  "=> TEST1\nImmediate output from TEST1\nOutput\r\nfrom\r\nTEST1\n"
  ---------------------------------------------------------^
at NUnit.ConsoleRunner.Tests.TestEventHandlerTests.MultipleEvents (System.String[] reports, System.String labels, System.String expected) <0x3548e80 + 0x000e7> in <filename unknown>:0
5) Failed : NUnit.ConsoleRunner.Tests.TestEventHandlerTests.MultipleEvents(System.String[],"After","=> TEST1\r\nImmediate output from TEST1\r\nOutput\r\nfrom\r\nTEST1\r\nPASSED => TEST1\r\n")
  Expected string length 71 but was 73. Strings differ at index 43.
  Expected: "...ediate output from TEST1\nOutput\nfrom\nTEST1\nPASSED => TEST1\n"
  But was:  "...ediate output from TEST1\nOutput\r\nfrom\r\nTEST1\nPASSED => TEST1\n"
  -----------------------------------------------^
at NUnit.ConsoleRunner.Tests.TestEventHandlerTests.Multi
```

**Comment by constructor-igor** [comment]
Hmmmm....
Expected result defined as
```c#
            new TestCaseData(
                SingleTestEvents,
                "Off",
                "Immediate output from TEST1\r\nOutput\r\nfrom\r\nTEST1\r\n"),
```
Before testing of result we change in expected string **\r\n** to **Environment.NewLine**
```c#
            if (Environment.NewLine != "\r\n")
                expected = expected.Replace("\r\n", Environment.NewLine);
            Assert.That(Output, Is.EqualTo(expected));
```

Actually, method **TestEventHandler.WriteOutputLine()** adds "WriteLine". But only one "\r\n" we see in actual result.
Please, could you help me to understand the issue?

```c#
        private void WriteOutputLine(string text, ColorStyle color)
        {
            using (new ColorConsole(color))
            {
                _outWriter.Write(text);

                // Some labels were being shown on the same line as the previous output
                if (!text.EndsWith("\n"))
                {
                    _outWriter.WriteLine();
                }
            }
        }
```

**Comment by constructor-igor** [comment]
@CharliePoole, @rprouse please, could you help me to understand issue with "\r\n"?

**Comment by rprouse** [comment]
@constructor-igor sorry this is taking so long to get back to you. I am on a new machine without a Linux VM to debug on. I am restoring my Ubuntu VM and will take a look once I get it set up.

**Comment by rprouse** [comment]
@constructor-igor something is up with my Linux VM. I've tried fixing it, but it is pooched so I am going to setup a new one. One thing I did notice is that in the actual output, the first `\r\n` is converted and the last one is, but not any in-between. I don't see anything in your code that should cause that, so I want to debug on Linux.

**Comment by constructor-igor** [comment]
@rprouse ok. unfortunately, I have not Linux system to investigate the issue. And I don't understand if the my changes lead to the failed test.

**Comment by rprouse** [comment]
I don't know why, but I cannot get an Ubuntu VM running on my new computer. I am downloading a newer iso and will give it another try. 

At first glance, it doesn't look like your code is directly causing the failures, but I need to debug it.

**Comment by rprouse** [comment]
I have a new Linux VM installed, but I am unable to debug because the projects target .NET 2.0 which Mono no longer supports.

image

I can't even build from the command line. @CharliePoole have we setup anything special on the Travis builds to get them to work, or is it because Travis starts with 3.2.8 and installs 4.x over it leaving the .NET 2.0 assemblies?

I am running Ubuntu 16.10 which installs Mono 4.2.1.0 by default.

**Comment by CharliePoole** [comment]
@rprouse I'm not sure, let me give it a try on one of my machines.

**Comment by rprouse** [comment]
@CharliePoole I didn't have a problem on my old Linux machines that go upgraded to Mono 4.x. I think this is a problem because this is a new machine that started with 4.x.

**Comment by rprouse** [comment]
Looking at the `/usr/lib/mono/2.0` directory on a couple of Linux boxes, on an older Ubuntu 15.04 machine, the directory contains all of the .NET assemblies. I think that machine started with Mono 3.2.8 and I upgraded it to 4.2.3.

On the Ubuntu 16.10 box that I setup this morning, the version of mono that was installed is 4.2.1 and the `/usr/lib/mono/2.0` directory is empty.

It looks like [Mono dropping support for pre-4.5 versions of .NET](http://www.mono-project.com/docs/about-mono/releases/4.0.0/#dropped-support-for-old-frameworks) might be starting to effect us as Linux distros start shipping Mono 4.x by default. It might be something we need to start thinking about...

**Comment by rprouse** [comment]
I finally got my old VM running and managed to build and debug the tests. Turns out that the problem was as simple as some hard coded `/r/n`'s in the unit tests. Just hard to pick out. I've made the fix and pushed to this branch.

@CharliePoole should we create an issue for the team to discuss building on newer Linux distros with the changes to Mono? It effects this repo and the framework.

**Comment by rprouse** [comment]
The Linux builds on Travis passed, Mac builds appear to still be not running on Travis so I am going to override and merge.

**Comment by CharliePoole** [comment]
@rprouse This was marked "Do not merge" I'm not sure if all the functionality is actually finished. @constructor-igor What do you think?

**Comment by rprouse** [comment]
Sorry, I thought that was because @constructor-igor couldn't edit your comment. I thought he had completed it and it looked complete when I tested it locally, but I might have misread what I was seeing when I tested each of the command line options.

@constructor-igor what is the status of this? Should I revert the merge?

**Comment by constructor-igor** [comment]
@CharliePoole and @rprouse Right now I don't know about not completed use cases, Please, could you help to understand how to create full set of tests. I guess, the test can provide us answer if the feature implemented.

**Pull request merged**
