### PR TITLE
More data for start-run element

### PR DESCRIPTION
**Pull request by elv1s42**
Adding new data to `start-run` element:

 - `engine-version` as a new attribute for `start-run` element
 - `clr-version` as a new attribute for `start-run` element
 - `start-time` as a new attribute for `start-run` element
 - `command-line` as a child of `start-run` node

Resolving #625

### CODE REVIEW

**Comment by elv1s42** [comment]
Please do not merge this pull request as I still need to add some tests to cover new fuctionality

**Comment by elv1s42** [comment]
@CharliePoole and @ChrisMaddock, please take a look at this when you have some time. 
Thank you

**Comment by CharliePoole** [comment]
I think more team members ought to comment on the desired API rather than merely reviewing how it is coded and merging. Once we merge with BeforeAndAfter, we have yet another legacy option that we will feel obligated to maintain forever. :disappointed: 

That said, I'll take a look at the code next. :smiley:

**Comment by rprouse** [comment]
@CharliePoole am I missing something or are your comments for a different PR? I don't see anything about the `All` and `BeforeAndAfter` flags in this PR?

**Comment by rprouse** [comment]
I think @CharliePoole's comments apply to #630, not this PR. We just need a second review here. Looks good, thanks.

**Comment by CharliePoole** [comment]
Sorry... yes, that was a comment about #630.

**Pull request merged**
